# Generated by Django 2.2.5 on 2019-12-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HCI', '0017_auto_20191202_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Spam', "It's a spam"), ('Outdated', 'Some fields need to be updated/filled'), ('Duplicated', 'This is duplicated')], max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityReport',
            fields=[
                ('abstractreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.AbstractReport')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='HCI.University')),
            ],
            bases=('report.abstractreport',),
        ),
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('abstractreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.AbstractReport')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='HCI.Course')),
            ],
            bases=('report.abstractreport',),
        ),
    ]
