# Generated by Django 2.2.5 on 2019-12-03 01:08

import HCI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=HCI.models.generate_slug, editable=False, max_length=10, unique=True, verbose_name='Slug')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Course Name')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Course Code')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('category', models.CharField(choices=[('Human-Computer Interaction', 'Human-Computer Interaction'), ('Computational Mathematics', 'Computational Mathematics')], max_length=500, verbose_name='Category Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Most Recent Course Website')),
                ('prerequisites', models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Prerequisites')),
                ('core_for_major', models.BooleanField(verbose_name='Core for Major?')),
                ('last_taught', models.DateField(blank=True, null=True, verbose_name='Last Taught')),
                ('instructor', models.CharField(blank=True, max_length=100, verbose_name='Most Recent Instructor')),
                ('learning_goals', models.TextField(blank=True, verbose_name='Learning outcome/goals')),
                ('complete', models.BooleanField(default=False, verbose_name='Is it complete')),
                ('verified', models.BooleanField(default=False, verbose_name='Is it verified')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Criteria Name')),
                ('weight', models.FloatField(verbose_name='Criteria Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='Number of the Week in Which This Topic Is Taught')),
                ('description', models.CharField(max_length=800, verbose_name='Topic Description')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='University Name')),
                ('short_name', models.CharField(max_length=100, verbose_name='University Short Name')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='University Country')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='University State')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='University City')),
            ],
        ),
    ]
