# Generated by Django 2.2.5 on 2019-09-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='equivalent',
            field=models.ManyToManyField(blank=True, related_name='_course_equivalent_+', to='HCI.Course'),
        ),
    ]
