# Generated by Django 2.2.5 on 2019-12-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HCI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCI.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCI.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='equivalent',
            field=models.ManyToManyField(blank=True, related_name='_course_equivalent_+', to='HCI.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCI.University', verbose_name='University'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('week', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together={('name', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'university')},
        ),
    ]
