# Generated by Django 2.2.5 on 2019-09-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0002_auto_20190930_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HCI.Course', verbose_name='Course'),
            preserve_default=False,
        ),
    ]
