# Generated by Django 2.2.5 on 2019-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0002_auto_20191202_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Computational Mathematics', 'Computational Mathematics'), ('Human-Computer Interaction', 'Human-Computer Interaction')], max_length=500, verbose_name='Category Name'),
        ),
    ]
