# Generated by Django 2.2.5 on 2019-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0004_auto_20191210_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'United States of America'), ('Canada', 'Canada')], max_length=100, verbose_name='University Country'),
        ),
    ]
