# Generated by Django 2.2.5 on 2019-10-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0005_auto_20190930_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Is it complete'),
        ),
        migrations.AddField(
            model_name='course',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Is it verified'),
        ),
    ]
