# Generated by Django 2.2.5 on 2019-12-11 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0005_auto_20191210_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=800, verbose_name='Topic Description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='week',
            field=models.IntegerField(blank=True, verbose_name='Number of the Week in Which This Topic Is Taught'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, choices=[('Canada', 'Canada'), ('USA', 'United States of America')], max_length=100, verbose_name='University Country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
