# Generated by Django 2.2.9 on 2020-02-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0006_auto_20191210_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Human-Computer Interaction', 'Human-Computer Interaction'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=500, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'United States of America'), ('Canada', 'Canada')], max_length=100, verbose_name='University Country'),
        ),
    ]
