# Generated by Django 2.2.5 on 2019-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0011_auto_20191007_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(default=0, max_length=100, verbose_name='University Short Name'),
            preserve_default=False,
        ),
    ]
