# Generated by Django 2.2.5 on 2019-10-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0012_university_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=800, verbose_name='Topic Description'),
        ),
    ]
