# Generated by Django 2.2.5 on 2019-11-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0014_auto_20191104_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('HCI', 'Human-Computer Interaction'), ('MATH', 'Computational Mathematics')], default='HCI', max_length=500, verbose_name='Category Name'),
            preserve_default=False,
        ),
    ]
