# Generated by Django 2.2.6 on 2019-11-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0015_course_category'),
        ('HCI', '0014_auto_20191027_2113'),
    ]

    operations = [
    ]
