# Generated by Django 2.2.5 on 2019-12-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0016_merge_20191111_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Computational Mathematics', 'Computational Mathematics'), ('Human-Computer Interaction', 'Human-Computer Interaction')], max_length=500, verbose_name='Category Name'),
        ),
    ]
