# Generated by Django 2.2.5 on 2019-09-27 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course Name', models.CharField(blank=True, max_length=500, verbose_name='Course Name')),
                ('Course Code', models.CharField(blank=True, max_length=100, verbose_name='Course Code')),
                ('Course Description', models.TextField(blank=True, verbose_name='Course Description')),
                ('Course Website', models.URLField(null=True, verbose_name='Most Recent Course Website')),
                ('Course Prerequisites', models.CharField(max_length=500, null=True, verbose_name='Course Prerequisites')),
                ('Core for Major?', models.BooleanField(verbose_name='Core for Major?')),
                ('Last Taught', models.DateField(verbose_name='Last Taught')),
                ('Instructor', models.CharField(blank=True, max_length=100, verbose_name='Most Recent Instructor')),
                ('Learning Goals', models.TextField(blank=True, verbose_name='Learning outcome/goals')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number of the Week', models.IntegerField(verbose_name='Number of the Week in Which This Topic Is Taught')),
                ('Topic Description', models.CharField(max_length=500, verbose_name='Topic Description')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University Name', models.CharField(max_length=100, verbose_name='University Name')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criteria Name', models.CharField(blank=True, max_length=100, verbose_name='Criteria Name')),
                ('Criteria Weight', models.FloatField(verbose_name='Criteria Weight')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCI.Course', verbose_name='Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='University',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HCI.University', verbose_name='University'),
        ),
        migrations.AddField(
            model_name='course',
            name='equivalent',
            field=models.ManyToManyField(related_name='_course_equivalent_+', to='HCI.Course'),
        ),
    ]
