# Generated by Django 2.2.5 on 2019-09-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0004_auto_20190930_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Topic Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Number of the Week',
            new_name='week',
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='University Name'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'university')},
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together={('name', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('week', 'course')},
        ),
    ]
