# Generated by Django 2.2.5 on 2019-10-07 02:21

import HCI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0006_auto_20191004_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(default=HCI.models.generate_slug, max_length=10, verbose_name='Slug'),
        ),
    ]
