# Generated by Django 2.2.5 on 2019-10-07 02:22

import HCI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0007_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(default=HCI.models.generate_slug, editable=False, max_length=10, verbose_name='Slug'),
        ),
    ]
