# Generated by Django 2.2.6 on 2019-10-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCI', '0013_auto_20191010_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='University City'),
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='University Country'),
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='University State'),
        ),
    ]
